pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                 echo "pwd: ${pwd()}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    echo "pwd: ${pwd()}"
                     sh 'npm install -r requirements.txt'
                }
            }
        }

        stage('App Start') {
            steps {
                dir('frontend') {
                    sh 'npm start'
                }
            }
        }
    }
}
