pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                 echo "pwd: ${pwd()}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    echo "pwd: ${pwd()}"
                    sh '''
                      python3 -m venv .venv
                      .venv/bin/pip install --upgrade pip
                      .venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('App Start') {
            steps {
                dir('backend') {
                    sh 'python3 app.py'
                }
            }
        }
    }
}
